// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/proto/demo/v1/myservice.proto

package v1

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint64                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PaidPlan      bool                   `protobuf:"varint,4,opt,name=paid_plan,json=paidPlan,proto3" json:"paid_plan,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Subscriptions []string               `protobuf:"bytes,7,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetPaidPlan() bool {
	if x != nil {
		return x.PaidPlan
	}
	return false
}

func (x *CreateUserRequest) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint64                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PaidPlan      bool                   `protobuf:"varint,4,opt,name=paid_plan,json=paidPlan,proto3" json:"paid_plan,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Subscriptions []string               `protobuf:"bytes,7,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserResponse) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserResponse) GetPaidPlan() bool {
	if x != nil {
		return x.PaidPlan
	}
	return false
}

func (x *CreateUserResponse) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserResponse) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// grpc stream with large amount of data
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP(), []int{2}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResult) Reset() {
	*x = PutResult{}
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResult) ProtoMessage() {}

func (x *PutResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResult.ProtoReflect.Descriptor instead.
func (*PutResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_demo_v1_myservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP(), []int{4}
}

var File_pkg_proto_demo_v1_myservice_proto protoreflect.FileDescriptor

const file_pkg_proto_demo_v1_myservice_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/demo/v1/myservice.proto\x12\ademo.v1\x1a(third_party/vtprotobuf/vtproto/ext.proto\"\xd8\x01\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x04R\x03age\x12\x1b\n" +
	"\tpaid_plan\x18\x04 \x01(\bR\bpaidPlan\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\rsubscriptions\x18\a \x03(\tR\rsubscriptions\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\"\xd9\x01\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x04R\x03age\x12\x1b\n" +
	"\tpaid_plan\x18\x04 \x01(\bR\bpaidPlan\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\rsubscriptions\x18\a \x03(\tR\rsubscriptions\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\"!\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data:\x04\xa8\xa6\x1f\x01\"\v\n" +
	"\tPutResult\"\f\n" +
	"\n" +
	"GetRequest2\xb3\x01\n" +
	"\tMyService\x12G\n" +
	"\n" +
	"CreateUser\x12\x1a.demo.v1.CreateUserRequest\x1a\x1b.demo.v1.CreateUserResponse\"\x00\x12-\n" +
	"\x03Put\x12\x0e.demo.v1.Chunk\x1a\x12.demo.v1.PutResult\"\x00(\x01\x12.\n" +
	"\x03Get\x12\x13.demo.v1.GetRequest\x1a\x0e.demo.v1.Chunk\"\x000\x01B.Z,github.com/chyiyaqing/gcat/pkg/proto/demo/v1b\x06proto3"

var (
	file_pkg_proto_demo_v1_myservice_proto_rawDescOnce sync.Once
	file_pkg_proto_demo_v1_myservice_proto_rawDescData []byte
)

func file_pkg_proto_demo_v1_myservice_proto_rawDescGZIP() []byte {
	file_pkg_proto_demo_v1_myservice_proto_rawDescOnce.Do(func() {
		file_pkg_proto_demo_v1_myservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_demo_v1_myservice_proto_rawDesc), len(file_pkg_proto_demo_v1_myservice_proto_rawDesc)))
	})
	return file_pkg_proto_demo_v1_myservice_proto_rawDescData
}

var file_pkg_proto_demo_v1_myservice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_demo_v1_myservice_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: demo.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: demo.v1.CreateUserResponse
	(*Chunk)(nil),              // 2: demo.v1.Chunk
	(*PutResult)(nil),          // 3: demo.v1.PutResult
	(*GetRequest)(nil),         // 4: demo.v1.GetRequest
}
var file_pkg_proto_demo_v1_myservice_proto_depIdxs = []int32{
	0, // 0: demo.v1.MyService.CreateUser:input_type -> demo.v1.CreateUserRequest
	2, // 1: demo.v1.MyService.Put:input_type -> demo.v1.Chunk
	4, // 2: demo.v1.MyService.Get:input_type -> demo.v1.GetRequest
	1, // 3: demo.v1.MyService.CreateUser:output_type -> demo.v1.CreateUserResponse
	3, // 4: demo.v1.MyService.Put:output_type -> demo.v1.PutResult
	2, // 5: demo.v1.MyService.Get:output_type -> demo.v1.Chunk
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_demo_v1_myservice_proto_init() }
func file_pkg_proto_demo_v1_myservice_proto_init() {
	if File_pkg_proto_demo_v1_myservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_demo_v1_myservice_proto_rawDesc), len(file_pkg_proto_demo_v1_myservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_demo_v1_myservice_proto_goTypes,
		DependencyIndexes: file_pkg_proto_demo_v1_myservice_proto_depIdxs,
		MessageInfos:      file_pkg_proto_demo_v1_myservice_proto_msgTypes,
	}.Build()
	File_pkg_proto_demo_v1_myservice_proto = out.File
	file_pkg_proto_demo_v1_myservice_proto_goTypes = nil
	file_pkg_proto_demo_v1_myservice_proto_depIdxs = nil
}
