// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: myservice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint64                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PaidPlan      bool                   `protobuf:"varint,4,opt,name=paid_plan,json=paidPlan,proto3" json:"paid_plan,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Subscriptions []string               `protobuf:"bytes,7,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_myservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_myservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetPaidPlan() bool {
	if x != nil {
		return x.PaidPlan
	}
	return false
}

func (x *CreateUserRequest) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint64                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	PaidPlan      bool                   `protobuf:"varint,4,opt,name=paid_plan,json=paidPlan,proto3" json:"paid_plan,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Subscriptions []string               `protobuf:"bytes,7,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_myservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_myservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_myservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserResponse) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserResponse) GetPaidPlan() bool {
	if x != nil {
		return x.PaidPlan
	}
	return false
}

func (x *CreateUserResponse) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserResponse) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_myservice_proto protoreflect.FileDescriptor

const file_myservice_proto_rawDesc = "" +
	"\n" +
	"\x0fmyservice.proto\x12\ademo.v1\"\xd8\x01\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x04R\x03age\x12\x1b\n" +
	"\tpaid_plan\x18\x04 \x01(\bR\bpaidPlan\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\rsubscriptions\x18\a \x03(\tR\rsubscriptions\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\"\xd9\x01\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x04R\x03age\x12\x1b\n" +
	"\tpaid_plan\x18\x04 \x01(\bR\bpaidPlan\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x04R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\rsubscriptions\x18\a \x03(\tR\rsubscriptions\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email2T\n" +
	"\tMyService\x12G\n" +
	"\n" +
	"CreateUser\x12\x1a.demo.v1.CreateUserRequest\x1a\x1b.demo.v1.CreateUserResponse\"\x00B.Z,github.com/chyiyaqing/gcat/pkg/proto/demo/v1b\x06proto3"

var (
	file_myservice_proto_rawDescOnce sync.Once
	file_myservice_proto_rawDescData []byte
)

func file_myservice_proto_rawDescGZIP() []byte {
	file_myservice_proto_rawDescOnce.Do(func() {
		file_myservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myservice_proto_rawDesc), len(file_myservice_proto_rawDesc)))
	})
	return file_myservice_proto_rawDescData
}

var file_myservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_myservice_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: demo.v1.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: demo.v1.CreateUserResponse
}
var file_myservice_proto_depIdxs = []int32{
	0, // 0: demo.v1.MyService.CreateUser:input_type -> demo.v1.CreateUserRequest
	1, // 1: demo.v1.MyService.CreateUser:output_type -> demo.v1.CreateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myservice_proto_init() }
func file_myservice_proto_init() {
	if File_myservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myservice_proto_rawDesc), len(file_myservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myservice_proto_goTypes,
		DependencyIndexes: file_myservice_proto_depIdxs,
		MessageInfos:      file_myservice_proto_msgTypes,
	}.Build()
	File_myservice_proto = out.File
	file_myservice_proto_goTypes = nil
	file_myservice_proto_depIdxs = nil
}
