// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/proto/users/v1/users.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserV1Service_Echo_FullMethodName = "/users.v1.UserV1Service/Echo"
)

// UserV1ServiceClient is the client API for UserV1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserV1ServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type userV1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserV1ServiceClient(cc grpc.ClientConnInterface) UserV1ServiceClient {
	return &userV1ServiceClient{cc}
}

func (c *userV1ServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, UserV1Service_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserV1ServiceServer is the server API for UserV1Service service.
// All implementations must embed UnimplementedUserV1ServiceServer
// for forward compatibility.
type UserV1ServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	mustEmbedUnimplementedUserV1ServiceServer()
}

// UnimplementedUserV1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserV1ServiceServer struct{}

func (UnimplementedUserV1ServiceServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedUserV1ServiceServer) mustEmbedUnimplementedUserV1ServiceServer() {}
func (UnimplementedUserV1ServiceServer) testEmbeddedByValue()                       {}

// UnsafeUserV1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserV1ServiceServer will
// result in compilation errors.
type UnsafeUserV1ServiceServer interface {
	mustEmbedUnimplementedUserV1ServiceServer()
}

func RegisterUserV1ServiceServer(s grpc.ServiceRegistrar, srv UserV1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserV1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserV1Service_ServiceDesc, srv)
}

func _UserV1Service_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserV1ServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserV1Service_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserV1ServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// UserV1Service_ServiceDesc is the grpc.ServiceDesc for UserV1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserV1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.v1.UserV1Service",
	HandlerType: (*UserV1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _UserV1Service_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/users/v1/users.proto",
}
